/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Timeline.Core.Level;

/**
 * 
 * @author Glauber
 */
public class Store extends javax.swing.JPanel {

	/**
	 * Creates new form Store2
	 */
	public Store() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblStatusTower = new javax.swing.JLabel();
		lblLife = new javax.swing.JLabel();
		lblGold = new javax.swing.JLabel();
		lblNomeUsuario = new javax.swing.JLabel();
		jRadioButton10 = new javax.swing.JRadioButton();
		jRadioButton9 = new javax.swing.JRadioButton();
		jRadioButton8 = new javax.swing.JRadioButton();
		jRadioButton7 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		b2 = new javax.swing.JRadioButton();
		b1 = new javax.swing.JRadioButton();
		btnPausar = new javax.swing.JRadioButton();
		btnSair = new javax.swing.JRadioButton();
		jLabel1 = new javax.swing.JLabel();

		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lblStatusTower.setForeground(new java.awt.Color(255, 255, 255));
		add(lblStatusTower, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				663, 21, 200, 100));

		lblLife.setFont(new java.awt.Font("Segoe UI", 0, 12));
		lblLife.setForeground(new java.awt.Color(255, 255, 255));
		add(lblLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 97,
				170, 20));

		lblGold.setFont(new java.awt.Font("Segoe UI", 0, 12));
		lblGold.setForeground(new java.awt.Color(255, 255, 255));
		add(lblGold, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60,
				170, 20));

		lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
		lblNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
		add(lblNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				140, 27, 170, 20));

		jRadioButton10.setContentAreaFilled(false);
		jRadioButton10.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton10.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				598, 74, -1, -1));

		jRadioButton9.setContentAreaFilled(false);
		jRadioButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton9.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				533, 74, -1, -1));

		jRadioButton8.setContentAreaFilled(false);
		jRadioButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton8.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				468, 74, -1, -1));

		jRadioButton7.setContentAreaFilled(false);
		jRadioButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton7.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				403, 74, -1, -1));

		jRadioButton6.setContentAreaFilled(false);
		jRadioButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton6.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				338, 74, -1, -1));

		jRadioButton5.setContentAreaFilled(false);
		jRadioButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton5.setPreferredSize(new java.awt.Dimension(50, 50));
		jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton5ActionPerformed(evt);
			}
		});
		add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				598, 16, -1, -1));

		jRadioButton4.setContentAreaFilled(false);
		jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton4.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				533, 16, -1, -1));

		jRadioButton3.setContentAreaFilled(false);
		jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		jRadioButton3.setPreferredSize(new java.awt.Dimension(50, 50));
		add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				468, 16, -1, -1));

		b2.setContentAreaFilled(false);
		b2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/SemTorre.png"))); // NOI18N
		b2.setPreferredSize(new java.awt.Dimension(50, 50));
		add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 16, -1,
				-1));

		b1.setContentAreaFilled(false);
		b1.setPreferredSize(new java.awt.Dimension(50, 50));
		add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 16, -1,
				-1));

		btnPausar.setContentAreaFilled(false);
		btnPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/Pausar.png"))); // NOI18N
		btnPausar.setPreferredSize(new java.awt.Dimension(100, 40));
		add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870,
				20, -1, -1));

		btnSair.setContentAreaFilled(false);
		btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/Sair.png"))); // NOI18N
		btnSair.setPreferredSize(new java.awt.Dimension(100, 40));
		btnSair.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSairActionPerformed(evt);
			}
		});
		add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80,
				-1, -1));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Menu/Store/FundoStore.png"))); // NOI18N
		add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0,
				1000, 140));
	}// </editor-fold>//GEN-END:initComponents

	private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton5ActionPerformed

	private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSairActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JRadioButton b1;
	public javax.swing.JRadioButton b2;
	public javax.swing.JRadioButton btnPausar;
	public javax.swing.JRadioButton btnSair;
	public javax.swing.JLabel jLabel1;
	public javax.swing.JRadioButton jRadioButton10;
	public javax.swing.JRadioButton jRadioButton3;
	public javax.swing.JRadioButton jRadioButton4;
	public javax.swing.JRadioButton jRadioButton5;
	public javax.swing.JRadioButton jRadioButton6;
	public javax.swing.JRadioButton jRadioButton7;
	public javax.swing.JRadioButton jRadioButton8;
	public javax.swing.JRadioButton jRadioButton9;
	public javax.swing.JLabel lblGold;
	public javax.swing.JLabel lblLife;
	public javax.swing.JLabel lblNomeUsuario;
	public javax.swing.JLabel lblStatusTower;
	// End of variables declaration//GEN-END:variables
}
